In [4]:

import numpy

world_alcohol = numpy.genfromtxt("D:\\Onedrive\\Documents\\codes\\AI\\machine-learning\\world_alcohol.txt",delimiter=',',dtype=str)

print(type(world_alcohol))# 整体类型
print(world_alcohol)
#print(help(numpy.genfromtxt))#查文档!


<class 'numpy.ndarray'>
[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ...
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]


In [5]:
vector = numpy.array([5,10,15,20])#转化成了矩阵格式
print(vector)


[ 5 10 15 20]


In [6]:
matrix = numpy.array([[5,10,15],[20,25,30],[35,40,45]])
print(matrix)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [7]:
vector = numpy.array([1,2,3,4])
print(vector.shape)
# 取数据
matrix = numpy.array([[5,10,15],[20,25,30],[35,40,45]])
print(matrix.shape)


(4,)
(3, 3)


In [8]:
import numpy 
numbers1 = numpy.array([1,2,3,4.0])
numbers2 = numpy.array([1,2,3,4])
print(numbers1)
print(numbers2)
print(numbers1.dtype)
print(numbers2.dtype)

[1. 2. 3. 4.]
[1 2 3 4]
float64
int32


In [9]:
# 取数据

import numpy

world_alcohol = numpy.genfromtxt("D:\\Onedrive\\Documents\\codes\\AI\\machine-learning\\world_alcohol.txt",delimiter=',',dtype=str)

#根据索引取数据
uruguay_other_1996 = world_alcohol[1,4]# 这里用中括号
third_country = world_alcohol[2,2]
print(uruguay_other_1996)
print(third_country)


vector = numpy.array([1,2,3,4])
print(vector[0:3])#开区间，不包含第三个数

matrix = numpy.array([[5,10,15],[20,25,30],[35,40,45]])
print(matrix[:,1])
print(matrix[1,:])
print(matrix[:,0:2])

0
Uruguay
[1 2 3]
[10 25 40]
[20 25 30]
[[ 5 10]
 [20 25]
 [35 40]]


In [22]:
# 做判断 
import numpy
vector  = numpy.array([5,10,15,20])
equal_to_ten = (vector == 10)
print(equal_to_ten)
print(vector[equal_to_ten])#当成索引

matrix = numpy.array([[5,10,15],[20,25,30],[35,40,45]])
second_column_25= (matrix[:,1] == 25)
print(second_column_25)
print(matrix[second_column_25,:])

[False  True False False]
[10]
[False  True False]
[[20 25 30]]
