In [7]:

import numpy

world_alcohol = numpy.genfromtxt("D:\\Onedrive\\Documents\\codes\\AI\\machine-learning\\world_alcohol.txt",delimiter=',',dtype=str)

print(type(world_alcohol))
print(world_alcohol)
print(help(numpy.genfromtxt))#查文档!


<class 'numpy.ndarray'>
[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ...
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]
Help on function genfromtxt in module numpy:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes')
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` c

In [7]:
vector = numpy.array([5,10,15,20])#转化成了矩阵格式
matrix = numpy.array([[5,10,15],[20,25,30],[35,40,45]])
print(vector)
print(matrix)


[ 5 10 15 20]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [8]:
vector = numpy.array([1,2,3,4])
print(vector.shape)
# 取数据
matrix = numpy.array([[5,10,15],[20,25,30],[35,40,45]])
print(matrix.shape)


(4,)
(3, 3)


In [2]:
import numpy 
numbers1 = numpy.array([1,2,3,4.0])
numbers2 = numpy.array([1,2,3,4])
print(numbers1)
print(numbers2)
print(numbers1.dtype)
print(numbers2.dtype)

[1. 2. 3. 4.]
[1 2 3 4]
float64
int32


In [14]:
# 取数据

import numpy

world_alcohol = numpy.genfromtxt("D:\\Onedrive\\Documents\\codes\\AI\\machine-learning\\world_alcohol.txt",delimiter=',',dtype=str)

#根据索引取数据
uruguay_other_1996 = world_alcohol[1,4]
third_country = world_alcohol[2,2]
print(uruguay_other_1996)
print(third_country)


vector = numpy.array([1,2,3,4])
print(vector[0:3])#开区间，不包含第三个数

matrix = numpy.array([[5,10,15],[20,25,30],[35,40,45]])
print(matrix[:,1])
print(matrix[1,:])
print(matrix[:,0:2])

0
Uruguay
[1 2 3]
[10 25 40]
[20 25 30]
[[ 5 10]
 [20 25]
 [35 40]]


In [22]:
# 做判断
import numpy
vector  = numpy.array([5,10,15,20])
equal_to_ten = (vector == 10)
print(equal_to_ten)
print(vector[equal_to_ten])#当成索引

matrix = numpy.array([[5,10,15],[20,25,30],[35,40,45]])
second_column_25= (matrix[:,1] == 25)
print(second_column_25)
print(matrix[second_column_25,:])

[False  True False False]
[10]
[False  True False]
[[20 25 30]]
