In [3]:
# 对矩阵的操作
import numpy as np
B = np.arange(3)
print(B)
#print np.exp(B)
print(np.sqrt(B))#sqrt 求根号

[0 1 2]
[0.         1.         1.41421356]


In [11]:
#矩阵->向量  向量->矩阵
a = np.floor(10*np.random.random((3,4)))#floor地板
#print(a)

## flatten the array
#print a.ravel() # 解开->变成一个向量
#a.shape = (6, 2)# 拉平了之后再变成(6,2)
#print(a) 
#print(a.T) # 求转置
print(a.resize(2,6))
print(a)

#If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:
#a.reshape(3,-1)#当我们指定其中一个维度的时候，另一个维度我们也知道了

SyntaxError: invalid syntax (<ipython-input-11-d4043d285e39>, line 11)

In [4]:
# 拼接

import numpy
a = np.floor(10*np.random.random((4,2,3)))# 从矩阵的角度来说，random的第一个数字就是多维度的
b = np.floor(10*np.random.random((2,2)))
print(a)
print ('---')
print(b)
print ('---')
print(np.hstack((a,b))) # 比如同一个对象一部分特征+ 另一个对象的一部分特征y as np

#print(np.vstack((a,b)))
#np.hstack((a,b))

[[[0. 2. 0.]
  [3. 6. 3.]]

 [[7. 4. 1.]
  [4. 3. 6.]]

 [[0. 0. 4.]
  [3. 7. 0.]]

 [[0. 6. 7.]
  [9. 4. 4.]]]
---
[[9. 3.]
 [6. 7.]]
---


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)

In [5]:
#切分
a = np.floor(10*np.random.random((2,12)))
#print (a)
#print (np.hsplit(a,3)) 平均分成3列
#print (np.hsplit(a,(3,4))   
r# Split a after the third and the fourth column
a = np.floor(10*np.random.random((12,2)))
print (a)
np.vsplit(a,3)

[[1. 9.]
 [9. 7.]
 [7. 9.]
 [6. 8.]
 [6. 9.]
 [1. 9.]
 [6. 5.]
 [0. 0.]
 [2. 3.]
 [9. 0.]
 [5. 4.]
 [0. 8.]]


[array([[1., 9.],
        [9., 7.],
        [7., 9.],
        [6., 8.]]),
 array([[6., 9.],
        [1., 9.],
        [6., 5.],
        [0., 0.]]),
 array([[2., 3.],
        [9., 0.],
        [5., 4.],
        [0., 8.]])]

In [40]:
#复制 1
#simple assignments make no copy of array objects or of their data
a = np.arange(12)
b = a
# a and b are two names for the same ndarray object
b is a
b.shape = 3,4
print (a.shape)
print (id(a))
print (id(b))

(3, 4)
82691200
82691200


In [43]:
# 浅复制
#The view method creates a new array object that looks at the same data.
c = a.view()# 这才是复制操作，但是他们是共用了值，所以一旦其中一个数字发生改变，两个数组同时发生改变
print(c is a)
c.shape = 2,6
#print a.shape
c[0,4] = 1234
print(a)

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [6]:
# 深复制
#The copy method makes a complete copy of the array and its data.
d = a.copy() 
d is a
d[0,0] = 9999
print (d) 
print (a)

[[9.999e+03 9.000e+00]
 [9.000e+00 7.000e+00]
 [7.000e+00 9.000e+00]
 [6.000e+00 8.000e+00]
 [6.000e+00 9.000e+00]
 [1.000e+00 9.000e+00]
 [6.000e+00 5.000e+00]
 [0.000e+00 0.000e+00]
 [2.000e+00 3.000e+00]
 [9.000e+00 0.000e+00]
 [5.000e+00 4.000e+00]
 [0.000e+00 8.000e+00]]
[[1. 9.]
 [9. 7.]
 [7. 9.]
 [6. 8.]
 [6. 9.]
 [1. 9.]
 [6. 5.]
 [0. 0.]
 [2. 3.]
 [9. 0.]
 [5. 4.]
 [0. 8.]]
