In [11]:
import numpy as np
print(np.arange(20))# 生成的是从0到19的数字
print(range(0,5))
data = np.sin(np.arange(20)).reshape(5,4)
print(data.shape)# 实际上生成的是5行4列的矩阵
print (data)
# Return indices of the maximum values along the given axis.
ind = data.argmax(axis=0)# 每一列参数值最大的索引值
print(help(data.argmax))
print (ind)
print(data.shape[1])
data_max = data[ind, range(data.shape[1])]# 我估计是range的问题

print (data_max)
all(data_max == data.max(axis=0))

# 这里涉及到一个关键的关键字就是range，range其实就是for

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
range(0, 5)
(5, 4)
[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
Help on built-in function argmax:

argmax(...) method of numpy.ndarray instance
    a.argmax(axis=None, out=None)
    
    Return indices of the maximum values along the given axis.
    
    Refer to `numpy.argmax` for full documentation.
    
    See Also
    --------
    numpy.argmax : equivalent function

None
[2 0 3 1]
4
[0.98935825 0.84147098 0.99060736 0.6569866 ]


True

In [12]:
import numpy as np
a = np.arange(0, 40, 10)
b = np.tile(a, (4, 5)) 
print(a)
print(b.shape)
print(b)

[ 0 10 20 30]
(4, 20)
[[ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]]


a = np.arange(0, 40, 10)
print a
print '---'
b = np.tile(a, (1, 4))
print b
#print a
#print b


In [5]:
import numpy as np
a = np.array([[4, 3, 5], [1, 2, 1]], np.uint32)
#a.fill(9)
#print(a)
b = np.sort(a, axis=1)
print(b)
#b
a.sort(axis=1)
print(a)
a = np.array([4, 3, 1, 2])
j = np.argsort(a)# 求索引
print (j)
print (a[j])

[[3 4 5]
 [1 1 2]]
[[3 4 5]
 [1 1 2]]
[2 3 1 0]
[1 2 3 4]
